"""first

Revision ID: 747f4a59ec50
Revises: 
Create Date: 2025-06-11 13:29:49.095856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747f4a59ec50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veterinary')
    op.drop_table('consultationservicelink')
    op.drop_table('consultation')
    op.drop_table('service')
    op.drop_table('client')
    op.drop_table('crmv')
    op.drop_table('animal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.VARCHAR(), nullable=False),
    sa.Column('species', sa.VARCHAR(), nullable=False),
    sa.Column('breed', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crmv',
    sa.Column('cpf', sa.VARCHAR(), nullable=False),
    sa.Column('graduation_institution', sa.VARCHAR(), nullable=False),
    sa.Column('year_of_graduation', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('service_name', sa.VARCHAR(), nullable=False),
    sa.Column('type_service', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation',
    sa.Column('animal_id', sa.INTEGER(), nullable=False),
    sa.Column('vet_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_in', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.Column('data_out', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultationservicelink',
    sa.Column('consultation_id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultation.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('consultation_id', 'service_id')
    )
    op.create_table('veterinary',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('crmv_id', sa.INTEGER(), nullable=False),
    sa.Column('specialization', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['crmv_id'], ['crmv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
